name: Bug
description: Standard bug report template, required for obtaining any support
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Stacktrace
      description: |
        The full stacktrace, if any.
        
        If it's being swallowed, please ensure the following Java properties are set: `"-Dclojure.main.report=stderr"`, `"-XX:-OmitStackTraceInFastThrow"`. 
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: |
        Version
      description: |
        The exact `nvd-clojure` version. If you are using `RELEASE`, please ensure and specify which version is that.
    validations:
      required: true
  - type: textarea
    id: java
    attributes:
      label: |
        Java version
      description: |
        The exact output of `java -version`.
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Installation compliance
      description: 
      options:
        - label: I have read again and made sure that I'm following **exactly** the instructions for my tool of choice ([Leiningen](https://github.com/rm-hull/nvd-clojure/tree/v3.5.0#leiningen), [Clojure CLI](https://github.com/rm-hull/nvd-clojure/tree/v3.5.0#clojure-cli), [Clojure CLI Tool](https://github.com/rm-hull/nvd-clojure/tree/v3.5.0#clojure-cli-tool)).
          required: true
        - label: I understand that false positives [can be skipped locally](https://github.com/rm-hull/nvd-clojure/tree/v3.5.0#configuration-options) and should be reported to [DependencyCheck](https://github.com/jeremylong/DependencyCheck).
          required: false
          
